### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by vip7kk** [Moosphan/app-code-obfuscation#1]
大佬，我下载仓库里的运行不了，错误：org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'cn.dorck.code.guarder', artifact: 'com.dorck.android:code-guard-plugin:0.1.0-LOCAL'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.dorck.android:code-guard-plugin:0.1.0-LOCAL')
  Searched in the following repositories:
    Google
    MavenRepo
    Gradle Central Plugin Repository
    MavenLocal(file:/C:/Users/YQ/.m2/repository/)

**Comment by Moosphan** [comment]
@vip7kk 目前插件还处于开发状态，尚未正式发布，等下周吧
