### ISSUE TITLE
集成gradle报错了

### ISSUE THREAD

**Issue by vip7kk** [Moosphan/app-code-obfuscation#2]
大佬，我引用库提示Your project may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
![image](https://github.com/Moosphan/app-code-obfuscation/assets/13134448/3982eae4-7a69-449c-a607-3ae4b4dc80ec)

**Comment by indieexplore** [comment]
@vip7kk 有完整的日志吗

**Comment by indieexplore** [comment]
我把gradle和agp版本和你提供的保持一致，没发现问题🤔

**Comment by Moosphan** [comment]
@vip7kk 如果还在用lacking的方式管理gradle依赖，那么可以基于下面的方式使用本插件：
> Project -> `build.gradle`：
```groovy
buildscript {
    ext.kotlin_version = "1.5.21"
    repositories {
        google()
        mavenCentral()
        maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/"}
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.2.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'cn.dorck.android:code-guard-plugin:0.0.1-SNAPSHOT'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/"}
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

> `app/build.gradle`：
```groovy
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'cn.dorck.code.guarder'
}

codeGuard {
    enable = true
    ...
}
```

**Comment by Moosphan** [comment]
> 我直接下载仓库demo运行，好像混淆没效果

**Comment by Moosphan** [comment]
> 我直接下载仓库demo运行，好像混淆没效果

执行 ./gradlew assembleRelease

**Comment by indieexplore** [comment]
@vip7kk demo里现在配置的是 `debug` 规则，并且约束了执行混淆的范围是 `com.dorck.app.obfuscate.simple`， 可以执行 `./gradlew assembleDebug` 后去对应的包路径下面看看有无混淆

**Comment by Moosphan** [comment]
> > @vip7kk demo里现在配置的是 `debug` 规则，并且约束了执行混淆的范围是 `com.dorck.app.obfuscate.simple`， 可以执行 `./gradlew assembleDebug` 后去对应的包路径下面看看有无混淆
> 
> 
> 
> ![image](https://github.com/Moosphan/app-code-obfuscation/assets/13134448/abe5ee6f-674d-4cbd-8616-cf36f01d2cbe)
> 
> 依然没效果.....

可以把 QQ 通过邮件发我，在线答疑🤓

**Comment by indieexplore** [comment]
@vip7kk 怎么会没效果，把你的build.gradke的插件配置都发我看下

**Comment by indieexplore** [comment]
> 打包会报错：Caused by: java.lang.AssertionError: symbolic reference class is not accessible: class sun.nio.ch.FileChannelImpl, from class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil (unnamed module @9597028)

这个是kt版本问题，不会中断打包流程，忽略就好，后面会适配

**Comment by indieexplore** [comment]
#### 1. 自己项目中没有使用 kts 语法的，如果是用的 `build.gradle`，groovy 语法是：
```groovy
HashSet<String> variants = new HashSet<>()
variants.add("debug")
codeGuard {
    enable = true
    variantConstraints = variants
}
```
#### 2. 下载demo无效果问题
- 确认下载的是最新的代码
- 打包方式用的是什么，Android studio 中的 `run` 吗？可以尝试终端执行 `./gradlew :app:assembleDebug` 看看效果

**Comment by indieexplore** [comment]
@vip7kk 有更完整的信息吗，只看到一个类似数组越界的错，但没有定位到具体报错的地方
