### ISSUE TITLE
能否做到混淆方法名字，目前只能添加垃圾代码

### ISSUE THREAD

**Issue by AndroidHJS** [Moosphan/app-code-obfuscation#3]

**Comment by indieexplore** [comment]
@AndroidHJS 你的意思是指混淆apk中原有方法的名字吗

**Comment by AndroidHJS** [comment]
对的

**Comment by AndroidHJS** [comment]
还有属性名

**Comment by indieexplore** [comment]
@AndroidHJS 原有类的方法和属性可以使用 proguard 来做

**Comment by AndroidHJS** [comment]
想自定义 感觉太简单有方案吗 能提供一下思路吗

**Comment by Moosphan** [comment]
> 想自定义 感觉 proguard混淆的太简单了，能够反编译   可以多少看出一点

proguard 可以自定义混淆字典的，插件也只是实现它没有的功能

**Comment by AndroidHJS** [comment]
> > 想自定义 感觉 proguard混淆的太简单了，能够反编译 可以多少看出一点
> 
> 老兄，你生成垃圾代码有效果？

可以改改方法名，现在手动改 感觉有点用
