### ISSUE TITLE
设置genClassCount报错

### ISSUE THREAD

**Issue by vip7kk** [Moosphan/app-code-obfuscation#5]
设置了genClassCount属性后，打包报错提示：Required: SUB_PROJECTS, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

**Comment by indieexplore** [comment]
@vip7kk 版本更新到 `0.1.0-beta`，今天刚发布的版本才支持 `genClassCount`

**Comment by indieexplore** [comment]
@vip7kk 提供一下配置信息，只在app模块使用的吗

**Comment by indieexplore** [comment]
@vip7kk 和kt没关系，你用demo工程试试看

**Comment by indieexplore** [comment]
> > @vip7kk 和kt没关系，你用demo工程试试看
> 
> demo可以，我集成就报错，邪门了

项目级别的 `build.gradle` 依赖了哪些插件，发我看看

**Comment by indieexplore** [comment]
> > > > @vip7kk 和kt没关系，你用demo工程试试看
> > > 
> > > 
> > > demo可以，我集成就报错，邪门了
> > 
> > 
> > 项目级别的 `build.gradle` 依赖了哪些插件，发我看看
> 
> 我擦，我知道是什么原因报错了，我集成了一个三方混淆插件就不行，我注释掉那个三方混淆插件就可以，不能和第三方混淆插件共同使用么

应该是的，第三方混淆插件可能也是基于ASM实现的，或者调整下 `app` 模块 `build.gradle` 中插件的引用顺序看看，把当前插件放在最后

**Comment by indieexplore** [comment]
@vip7kk 是本插件导致的吗，用的什么第三方混淆插件，我到时候试试看

**Comment by indieexplore** [comment]
@vip7kk 这个dprotect插件太流氓了，在tranform中插入任务执行，要一起用的话只能改它源码了，我后面找时间看看改一下
